import { PERMISSIONS, type Permission } from '@/lib/constants/permissions'
import { ROLES, type Role } from '@/lib/constants/roles'

/** Flat list of every permission — used for Super Admin access */
export const ALL_PERMISSIONS: Permission[] = Object.values(PERMISSIONS).flatMap(
  (group) => Object.values(group)
) as Permission[]

/** Employee — self-service attendance only */
export const EMPLOYEE_PERMISSIONS: Permission[] = [
  PERMISSIONS.ATTENDANCE.MY_VIEW,
  PERMISSIONS.ATTENDANCE.MY_MANAGE,
]

/** HR / manager — full attendance module + HRMS screens */
export const HR_MANAGER_PERMISSIONS: Permission[] = [
  PERMISSIONS.DASHBOARD.VIEW,
  PERMISSIONS.HRMS.DASHBOARD_VIEW,
  PERMISSIONS.EMPLOYEES.VIEW,
  PERMISSIONS.EMPLOYEES.CREATE,
  PERMISSIONS.EMPLOYEES.UPDATE,
  PERMISSIONS.EMPLOYEES.DELETE,
  PERMISSIONS.EMPLOYEES.EXPORT,
  PERMISSIONS.ATTENDANCE.DASHBOARD_VIEW,
  PERMISSIONS.ATTENDANCE.DAILY_VIEW,
  PERMISSIONS.ATTENDANCE.MY_VIEW,
  PERMISSIONS.ATTENDANCE.MY_MANAGE,
  PERMISSIONS.ATTENDANCE.CALENDAR_VIEW,
  PERMISSIONS.ATTENDANCE.CORRECTIONS_VIEW,
  PERMISSIONS.ATTENDANCE.CORRECTIONS_MANAGE,
  PERMISSIONS.ATTENDANCE.SHIFTS_MANAGE,
  PERMISSIONS.ATTENDANCE.OVERTIME_VIEW,
  PERMISSIONS.ATTENDANCE.OVERTIME_MANAGE,
  PERMISSIONS.ATTENDANCE.HOLIDAYS_MANAGE,
  PERMISSIONS.ATTENDANCE.REPORTS_VIEW,
  PERMISSIONS.ATTENDANCE.SETTINGS_MANAGE,
  PERMISSIONS.ATTENDANCE.EXPORT,
  PERMISSIONS.LEAVE.VIEW,
  PERMISSIONS.LEAVE.CREATE,
  PERMISSIONS.LEAVE.APPROVE,
  PERMISSIONS.LEAVE.REJECT,
  PERMISSIONS.PAYROLL.VIEW,
  PERMISSIONS.RECRUITMENT.VIEW,
  PERMISSIONS.PERFORMANCE.VIEW,
  PERMISSIONS.DOCUMENTS.VIEW,
  PERMISSIONS.REPORTS.VIEW,
]

export const ROLE_PERMISSION_PRESETS: Partial<Record<Role, Permission[]>> = {
  [ROLES.SUPER_ADMIN]: ALL_PERMISSIONS,
  [ROLES.ADMIN]: ALL_PERMISSIONS,
  [ROLES.EMPLOYEE]: EMPLOYEE_PERMISSIONS,
  [ROLES.HR_MANAGER]: HR_MANAGER_PERMISSIONS,
  [ROLES.HR_EXECUTIVE]: HR_MANAGER_PERMISSIONS,
  [ROLES.MANAGER]: [
    PERMISSIONS.DASHBOARD.VIEW,
    PERMISSIONS.HRMS.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE.DASHBOARD_VIEW,
    PERMISSIONS.ATTENDANCE.DAILY_VIEW,
    PERMISSIONS.ATTENDANCE.MY_VIEW,
    PERMISSIONS.ATTENDANCE.MY_MANAGE,
    PERMISSIONS.ATTENDANCE.CALENDAR_VIEW,
    PERMISSIONS.ATTENDANCE.CORRECTIONS_VIEW,
    PERMISSIONS.ATTENDANCE.CORRECTIONS_MANAGE,
    PERMISSIONS.ATTENDANCE.OVERTIME_VIEW,
    PERMISSIONS.ATTENDANCE.OVERTIME_MANAGE,
    PERMISSIONS.ATTENDANCE.REPORTS_VIEW,
    PERMISSIONS.LEAVE.VIEW,
    PERMISSIONS.LEAVE.APPROVE,
    PERMISSIONS.LEAVE.REJECT,
  ],
}

export function getPermissionsForRoles(roles: Role[]): Permission[] {
  if (roles.includes(ROLES.SUPER_ADMIN) || roles.includes(ROLES.ADMIN)) {
    return ALL_PERMISSIONS
  }

  const merged = new Set<Permission>()
  for (const role of roles) {
    const preset = ROLE_PERMISSION_PRESETS[role]
    if (preset) {
      preset.forEach((permission) => merged.add(permission))
    }
  }
  return [...merged]
}
