export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ME: '/auth/me',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
  },
  EMPLOYEES: {
    BASE: '/employees',
    BY_ID: (id: string) => `/employees/${id}`,
    SEARCH: '/employees/search',
  },
  ATTENDANCE: {
    BASE: '/attendance',
    DASHBOARD: '/attendance/dashboard',
    DAILY: '/attendance/daily',
    MY: '/attendance/my',
    CALENDAR: '/attendance/calendar',
    SESSION: '/attendance/session',
    CHECK_IN: '/attendance/check-in',
    CHECK_OUT: '/attendance/check-out',
    CORRECTIONS: '/attendance/corrections',
    SHIFTS: '/attendance/shifts',
    SHIFT_BY_ID: (id: string) => `/attendance/shifts/${id}`,
    HOLIDAYS: '/attendance/holidays',
    HOLIDAY_BY_ID: (id: string) => `/attendance/holidays/${id}`,
    OVERTIME: '/attendance/overtime',
    OVERTIME_APPROVE: (id: string) => `/attendance/overtime/${id}/approve`,
    OVERTIME_REJECT: (id: string) => `/attendance/overtime/${id}/reject`,
    REPORTS: '/attendance/reports/types',
    REPORTS_GENERATE: '/attendance/reports/generate',
    SETTINGS: '/attendance/settings',
    BY_ID: (id: string) => `/attendance/${id}`,
  },
  LEAVE: {
    BASE: '/leave',
    BY_ID: (id: string) => `/leave/${id}`,
    APPROVE: (id: string) => `/leave/${id}/approve`,
    REJECT: (id: string) => `/leave/${id}/reject`,
  },
  PAYROLL: {
    BASE: '/payroll',
    BY_ID: (id: string) => `/payroll/${id}`,
    GENERATE: '/payroll/generate',
  },
  RECRUITMENT: {
    BASE: '/recruitment',
    BY_ID: (id: string) => `/recruitment/${id}`,
  },
  PERFORMANCE: {
    BASE: '/performance',
    BY_ID: (id: string) => `/performance/${id}`,
  },
  DEPARTMENTS: {
    BASE: '/departments',
  },
  DESIGNATIONS: {
    BASE: '/designations',
  },
} as const
