export const API_ENDPOINTS = {
  AUTH: {
    LOGIN: '/auth/login',
    LOGOUT: '/auth/logout',
    REFRESH: '/auth/refresh',
    FORGOT_PASSWORD: '/auth/forgot-password',
    RESET_PASSWORD: '/auth/reset-password',
    ME: '/auth/me',
  },
  USERS: {
    BASE: '/users',
    BY_ID: (id: string) => `/users/${id}`,
  },
  ROLE_PRIVILEGES: {
    BASE: '/role-privileges',
    RESET: (role: string) => `/role-privileges/${role}/reset`,
  },
  EMPLOYEES: {
    BASE: '/employees',
    BY_ID: (id: string) => `/employees/${id}`,
    SEARCH: '/employees/search',
  },
  ATTENDANCE: {
    BASE: '/attendance',
    DASHBOARD: '/attendance/dashboard',
    DAILY: '/attendance/daily',
    MY: '/attendance/my',
    CALENDAR: '/attendance/calendar',
    SESSION: '/attendance/session',
    CHECK_IN: '/attendance/check-in',
    CHECK_OUT: '/attendance/check-out',
    CORRECTIONS: '/attendance/corrections',
    SHIFTS: '/attendance/shifts',
    SHIFT_BY_ID: (id: string) => `/attendance/shifts/${id}`,
    HOLIDAYS: '/attendance/holidays',
    HOLIDAY_BY_ID: (id: string) => `/attendance/holidays/${id}`,
    OVERTIME: '/attendance/overtime',
    OVERTIME_APPROVE: (id: string) => `/attendance/overtime/${id}/approve`,
    OVERTIME_REJECT: (id: string) => `/attendance/overtime/${id}/reject`,
    REPORTS: '/attendance/reports/types',
    REPORTS_GENERATE: '/attendance/reports/generate',
    SETTINGS: '/attendance/settings',
    BY_ID: (id: string) => `/attendance/${id}`,
  },
  LEAVE: {
    BASE: '/leave',
    BY_ID: (id: string) => `/leave/${id}`,
    APPROVE: (id: string) => `/leave/${id}/approve`,
    REJECT: (id: string) => `/leave/${id}/reject`,
    CANCEL: (id: string) => `/leave/${id}/cancel`,
  },
  PAYROLL: {
    BASE: '/payroll',
    BY_ID: (id: string) => `/payroll/${id}`,
    GENERATE: '/payroll/generate',
  },
  RECRUITMENT: {
    REQUISITIONS: '/recruitment/requisitions',
    REQUISITION_BY_ID: (id: string) => `/recruitment/requisitions/${id}`,
    CANDIDATES: '/recruitment/candidates',
    CANDIDATE_BY_ID: (id: string) => `/recruitment/candidates/${id}`,
    CANDIDATE_STATUS: (id: string) => `/recruitment/candidates/${id}/status`,
    INTERVIEWS: '/recruitment/interviews',
    OFFERS: '/recruitment/offers',
    APPROVALS: '/recruitment/approvals',
    APPROVAL_BY_ID: (id: string) => `/recruitment/approvals/${id}`,
    JOB_POSTINGS: '/recruitment/job-postings',
  },
  ONBOARDING: {
    BASE: '/onboarding',
    BY_ID: (id: string) => `/onboarding/${id}`,
    UPDATE: (id: string) => `/onboarding/${id}`,
    DOCUMENTS: '/onboarding/documents',
    UPLOAD_DOCUMENT: '/onboarding/documents/upload',
    VERIFY_DOCUMENT: (documentId: string) => `/onboarding/documents/${documentId}/verify`,
    BACKGROUND_VERIFICATIONS: '/onboarding/background',
    POLICY_ACCEPTANCES: '/onboarding/policies',
    ACCEPT_POLICY: (policyId: string) => `/onboarding/policies/${policyId}/accept`,
    ASSETS: '/onboarding/assets',
    ALLOCATE_ASSET: '/onboarding/assets/allocate',
    TASKS: '/onboarding/tasks',
    UPDATE_TASK: (taskId: string) => `/onboarding/tasks/${taskId}`,
    STATS: '/onboarding/stats',
    IT_TASKS: '/onboarding/it-tasks',
    MANAGER_TASKS: '/onboarding/manager-tasks',
    HR_TASKS: '/onboarding/hr-tasks',
  },
  PERFORMANCE: {
    BASE: '/performance',
    GOALS: '/performance/goals',
    GOAL_BY_ID: (id: string) => `/performance/goals/${id}`,
    // BY_ID: (id: string) => `/performance/${id}`,
  },
  DEPARTMENTS: {
    BASE: '/departments',
  },
  DESIGNATIONS: {
    BASE: '/designations',
  },
  NOTIFICATIONS: {
  BASE: '/notifications',
  MARK_ALL_READ: '/notifications/read-all',
},
} as const
