export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  FORGOT_PASSWORD: '/forgot-password',
  DASHBOARD: '/dashboard',

  HRMS: {
    ROOT: '/hrms',
    DASHBOARD: '/hrms',
    EMPLOYEES: '/hrms/employees',
    EMPLOYEE_NEW: '/hrms/employees/new',
    EMPLOYEE_DETAIL: (id: string) => `/hrms/employees/${id}`,
    EMPLOYEE_EDIT: (id: string) => `/hrms/employees/${id}/edit`,

    ATTENDANCE: '/hrms/attendance',
    ATTENDANCE_MY: '/hrms/attendance/my',
    ATTENDANCE_DAILY: '/hrms/attendance/daily',
    ATTENDANCE_CALENDAR: '/hrms/attendance/calendar',
    ATTENDANCE_CORRECTIONS: '/hrms/attendance/corrections',
    ATTENDANCE_SHIFTS: '/hrms/attendance/shifts',
    ATTENDANCE_OVERTIME: '/hrms/attendance/overtime',
    ATTENDANCE_HOLIDAYS: '/hrms/attendance/holidays',
    ATTENDANCE_REPORTS: '/hrms/attendance/reports',
    ATTENDANCE_SETTINGS: '/hrms/attendance/settings',

    LEAVE: '/hrms/leave',
    PAYROLL: '/hrms/payroll',
    RECRUITMENT: {
      DASHBOARD: '/hrms/recruitment',
      REQUISITION: '/hrms/recruitment/requisition',
      APPROVAL: '/hrms/recruitment/approval',
      POSTING: '/hrms/recruitment/posting',
      APPLICATIONS: '/hrms/recruitment/applications',
      SCREENING: '/hrms/recruitment/screening',
      SHORTLIST: '/hrms/recruitment/shortlist',
      INTERVIEW_SCHEDULE: '/hrms/recruitment/interview-schedule',
      EVALUATION: '/hrms/recruitment/evaluation',
      SELECTION: '/hrms/recruitment/selection',
      OFFER_GENERATE: '/hrms/recruitment/offer-generate',
      OFFER_ACCEPTED: '/hrms/recruitment/offer-accepted',
      CANDIDATE_APPLICATIONS: '/hrms/recruitment/candidate-applications', 
    },
    ONBOARDING: {
      DASHBOARD: '/hrms/onboarding',
      EMPLOYEES:'/hrms/onboarding/employees',
      PROFILE: (id: string) => `/hrms/onboarding/employees/${id}`,
      DOCUMENTS: '/hrms/onboarding/documents',
      VERIFICATION: '/hrms/onboarding/documents/verify',
      BACKGROUND: '/hrms/onboarding/background',
      HR_TASKS: '/hrms/onboarding/hr',
      IT_TASKS: '/hrms/onboarding/it',
      MANAGER_TASKS: '/hrms/onboarding/manager-tasks',
      ASSETS: '/hrms/onboarding/assets',
      SYSTEM_ACCESS: '/hrms/onboarding/system-access',
      ORIENTATION: '/hrms/onboarding/orientation',
      POLICY: '/hrms/onboarding/policy',
      ACTIVE: '/hrms/onboarding/active',
     
    },
    PERFORMANCE: '/hrms/performance',
    DOCUMENTS: '/hrms/documents',
    REPORTS: '/hrms/reports',
  },
} as const
